// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfhtuehccqejbqrflfca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmaHR1ZWhjY3FlamJxcmZsZmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzcxOTUsImV4cCI6MjA2NjUxMzE5NX0.JnsvnJSyKK8VjrDwAHXNGTRY8kwWnJ1tOTweSra0PBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);